# Generated by Django 4.0.3 on 2022-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='last_sent_time',
            field=models.DateTimeField(null=True),
        ),
    ]
