# Generated by Django 4.0.3 on 2022-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_reportconfig_last_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='last_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
